export const inputFormElements = [
  {
    name: "firstName",
    placeholder: "Enter first name",
    label: "First Name",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "lastName",
    placeholder: "Enter last name",
    label: "Last Name",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "email",
    placeholder: "Enter email",
    label: "Email",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    sm: 6,
    type: "email",
  },
  {
    name: "phone",
    placeholder: "Enter phone number",
    label: "Phone no",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    sm: 6,
    type: "number",
  },
  {
    name: "street",
    placeholder: "Enter street",
    label: "Street",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "city",
    placeholder: "Enter city name",
    label: "City",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "state",
    placeholder: "Enter state",
    label: "State",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "country",
    placeholder: "Enter country name",
    label: "Country",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "pincode",
    placeholder: "Enter pincode number",
    label: "Pincode",
    variant: "outlined",
    fulWidth: true,
    required: true,
    xs: 12,
    lg: 12,
    md: 12,
    sm: 12,
  },
];
